apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vdiclusters.kvdi.io
spec:
  group: kvdi.io
  names:
    kind: VDICluster
    listKind: VDIClusterList
    plural: vdiclusters
    singular: vdicluster
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VDICluster is the Schema for the vdiclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VDIClusterSpec defines the desired state of VDICluster
          properties:
            app:
              description: App configurations.
              properties:
                auditLog:
                  description: Whether to log auditing events to stdout
                  type: boolean
                corsEnabled:
                  description: Whether to add CORS headers to API requests
                  type: boolean
                image:
                  description: The image to use for the app instances. Defaults to
                    the public image matching the version of the currently running
                    manager.
                  type: string
                replicas:
                  description: The number of app replicas to run
                  format: int32
                  type: integer
                resources:
                  description: Resource requirements to place on the app pods
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
              type: object
            appNamespace:
              description: The namespace to provision application resurces in. Defaults
                to the `default` namespace
              type: string
            auth:
              description: Authentication configurations
              properties:
                adminSecret:
                  description: A secret where a generated admin password will be stored
                  type: string
                allowAnonymous:
                  description: Allow anonymous users to create desktop instances
                  type: boolean
                ldapAuth:
                  description: Use LDAP for authentication.
                  properties:
                    adminGroups:
                      description: Group DNs that are allowed administrator access
                        to the cluster. Kubernetes admins will still have the ability
                        to change configurations via the CRDs.
                      items:
                        type: string
                      type: array
                    bindCredentialsSecret:
                      description: If you'd rather create a separate k8s secret (instead
                        of the configured backend) for the LDAP credentials, set its
                        name here. The keys in the secret need to be defined in the
                        other fields still. Default is to use the secret backend.
                      type: string
                    bindPasswordSecretKey:
                      description: Similar to the `bindUserDNSecretKey`, but for the
                        location of the password secret. Defaults to `ldap-password`.
                      type: string
                    bindUserDNSecretKey:
                      description: If you want to use the built-in secrets backend
                        (vault or k8s currently), set this to either the name of the
                        secret in the vault path, or the key of the secret used in
                        `k8sSecret.secretName. In default configurations this is`
                        `kvdi-app-secrets`. Defaults to `ldap-userdn`.
                      type: string
                    tlsCACert:
                      description: The base64 encoded CA certificate to use when verifying
                        the TLS certificate of the LDAP server.
                      type: string
                    tlsInsecureSkipVerify:
                      description: Set to true to skip TLS verification of an `ldaps`
                        connection.
                      type: boolean
                    url:
                      description: The URL to the LDAP server.
                      type: string
                    userSearchBase:
                      description: The base scope to search for users in. Default
                        is to search the entire directory.
                      type: string
                  type: object
                localAuth:
                  description: Use local auth (secret-backed) authentication
                  type: object
                oidcAuth:
                  description: Use OIDC for authentication
                  properties:
                    adminGroups:
                      description: Groups that are allowed administrator access to
                        the cluster. Kubernetes admins will still have the ability
                        to change rbac configurations via the CRDs.
                      items:
                        type: string
                      type: array
                    allowNonGroupedReadOnly:
                      description: Set to true if the OIDC provider does not support
                        the "groups" claim (or any valid alternative) and/or you would
                        like to allow any authenticated user read-only access.
                      type: boolean
                    clientCredentialsSecret:
                      description: When creating your own kubernets secret with the
                        `clientIDKey` and `clientSecretKey`, set this to the name
                        of the created secret. It must be in the same namespace as
                        the manager and app instances.
                      type: string
                    clientIDKey:
                      description: When using the built-in secrets backend, the key
                        to where the client-id is stored. When configuring `clientCredentialsSecret`,
                        set this to the key in that secret. Defaults to `oidc-clientid`.
                      type: string
                    clientSecretKey:
                      description: Similar to `clientIDKey`, but for the location
                        of the client secret. Defaults to `oidc-clientsecret`.
                      type: string
                    groupScope:
                      description: If your OIDC provider does not return a `groups`
                        object, set this to the user attribute to use for binding
                        authenticated users to VDIRoles. Defaults to `groups`.
                      type: string
                    issuerURL:
                      description: The OIDC issuer URL used for discovery
                      type: string
                    redirectURL:
                      description: The redirect URL path configured in the OIDC provider.
                        This should be the full path where kvdi is hosted followed
                        by `/api/login`. For example, if `kvdi` is hosted at https://kvdi.local,
                        then this value should be set `https://kvdi.local/api/login`.
                      type: string
                    scopes:
                      description: The scopes to request with the authentication request.
                        Defaults to `["openid", "email", "profile", "groups"]`.
                      items:
                        type: string
                      type: array
                    tlsCACert:
                      description: The base64 encoded CA certificate to use when verifying
                        the TLS certificate of the OIDC provider.
                      type: string
                    tlsInsecureSkipVerify:
                      description: Set to true to skip TLS verification of an OIDC
                        provider.
                      type: boolean
                  type: object
              type: object
            imagePullSecrets:
              description: Pull secrets to use when pulling container images
              items:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              type: array
            secrets:
              description: Secrets backend configurations
              properties:
                k8sSecret:
                  description: Use a kubernetes secret for storing sensitive values.
                    If no other coniguration is provided then this is the fallback.
                  properties:
                    secretName:
                      description: The name of the secret backing the values. Default
                        is `<cluster-name>-app-secrets`.
                      type: string
                  type: object
                vault:
                  description: Use vault for storing sensitive values. Requires kubernetes
                    service account authentication.
                  properties:
                    address:
                      description: The full URL to the vault server. Same as the `VAULT_ADDR`
                        variable.
                      type: string
                    authRole:
                      description: The auth role to assume when authenticating against
                        vault. Defaults to `kvdi`.
                      type: string
                    caCertBase64:
                      description: The base64 encoded CA certificate for verifying
                        the vault server certificate.
                      type: string
                    insecure:
                      description: Set to true to disable TLS verification.
                      type: boolean
                    secretsPath:
                      description: The base path to store secrets in vault.
                      type: string
                    tlsServerName:
                      description: Optionally set the SNI when connecting using HTTPS.
                      type: string
                  required:
                  - address
                  type: object
              type: object
            userdataSpec:
              description: The configuration for user volumes. *NOTE:* Even though
                the controller will try to force the reclaim policy on created volumes
                to `Retain`, you may want to set it explicitly on your storage-class
                controller as an extra safeguard.
              properties:
                accessModes:
                  description: 'AccessModes contains the desired access modes the
                    volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1'
                  items:
                    type: string
                  type: array
                dataSource:
                  description: This field requires the VolumeSnapshotDataSource alpha
                    feature gate to be enabled and currently VolumeSnapshot is the
                    only supported data source. If the provisioner can support VolumeSnapshot
                    data source, it will create a new volume and data will be restored
                    to the volume at the same time. If the provisioner does not support
                    VolumeSnapshot data source, volume will not be created and the
                    failure will be reported as an event. In the future, we plan to
                    support more data source types and the behavior of the provisioner
                    may change.
                  properties:
                    apiGroup:
                      description: APIGroup is the group for the resource being referenced.
                        If APIGroup is not specified, the specified Kind must be in
                        the core API group. For any other third-party types, APIGroup
                        is required.
                      type: string
                    kind:
                      description: Kind is the type of resource being referenced
                      type: string
                    name:
                      description: Name is the name of resource being referenced
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                resources:
                  description: 'Resources represents the minimum resources the volume
                    should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources'
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                selector:
                  description: A label query over volumes to consider for binding.
                  properties:
                    matchExpressions:
                      description: matchExpressions is a list of label selector requirements.
                        The requirements are ANDed.
                      items:
                        description: A label selector requirement is a selector that
                          contains values, a key, and an operator that relates the
                          key and values.
                        properties:
                          key:
                            description: key is the label key that the selector applies
                              to.
                            type: string
                          operator:
                            description: operator represents a key's relationship
                              to a set of values. Valid operators are In, NotIn, Exists
                              and DoesNotExist.
                            type: string
                          values:
                            description: values is an array of string values. If the
                              operator is In or NotIn, the values array must be non-empty.
                              If the operator is Exists or DoesNotExist, the values
                              array must be empty. This array is replaced during a
                              strategic merge patch.
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      description: matchLabels is a map of {key,value} pairs. A single
                        {key,value} in the matchLabels map is equivalent to an element
                        of matchExpressions, whose key field is "key", the operator
                        is "In", and the values array contains only "value". The requirements
                        are ANDed.
                      type: object
                  type: object
                storageClassName:
                  description: 'Name of the StorageClass required by the claim. More
                    info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1'
                  type: string
                volumeMode:
                  description: volumeMode defines what type of volume is required
                    by the claim. Value of Filesystem is implied when not included
                    in claim spec. This is a beta feature.
                  type: string
                volumeName:
                  description: VolumeName is the binding reference to the PersistentVolume
                    backing this claim.
                  type: string
              type: object
          type: object
        status:
          description: VDIClusterStatus defines the observed state of VDICluster
          properties:
            ready:
              type: boolean
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
