apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: ubuntu-xfce
spec:
  desktop:
    image: ghcr.io/kvdi/kvdi:ubuntu-xfce4-latest
    imagePullPolicy: IfNotPresent
    allowRoot: true
  proxy:
    allowFileTransfer: true
  dind: 
    image: "docker:19-dind" # Defaults to latest which may have issues depending on your runtime
  tags:
    os: ubuntu
    desktop: xfce4
    applications: minimal

---
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: dosbox
spec:
  desktop:
    image: ghcr.io/kvdi/kvdi:dosbox-latest
    imagePullPolicy: IfNotPresent
    init: supervisord
  proxy:
    pulseServer: unix:///var/run/kvdi/pulse-server
  tags:
    os: ubuntu
    desktop: dosbox

---
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: qemu-kvm
spec:
  qemu:
    diskImage: ghcr.io/kvdi/kvdi:ubuntu-qemu-latest
    diskImagePullPolicy: IfNotPresent
    cpus: 4
    memory: 4096
    useCSI: false
  tags:
    kvm: "true"
    os: ubuntu