---
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: ubuntu-xfce
spec:
  desktop:
    image: ghcr.io/webmeshproj/desktop-ubuntu-base-xfce4:latest
    imagePullPolicy: IfNotPresent
    allowRoot: true
  proxy:
    image: ghcr.io/webmeshproj/vdi-proxy:latest
    allowFileTransfer: true
  dind: 
    image: "docker:19-dind" # Defaults to latest which may have issues depending on your runtime
  tags:
    os: ubuntu
    desktop: xfce4
    applications: minimal
---
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: ubuntu-kde
spec:
  desktop:
    image: ghcr.io/webmeshproj/desktop-ubuntu-base-kde:latest
    imagePullPolicy: IfNotPresent
    allowRoot: true
  proxy:
    image: ghcr.io/webmeshproj/vdi-proxy:latest
    allowFileTransfer: true
  tags:
    os: ubuntu
    desktop: xfce4
    applications: minimal
---
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: dosbox
spec:
  desktop:
    image: ghcr.io/webmeshproj/desktop-dosbox-base:latest
    imagePullPolicy: IfNotPresent
    init: supervisord
  proxy:
    image: ghcr.io/webmeshproj/vdi-proxy:latest
    pulseServer: unix:///var/run/kvdi/pulse-server
  tags:
    os: ubuntu
    desktop: dosbox
