# permissions for end users to edit sessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: session-editor-role
rules:
- apiGroups:
  - desktops.kvdi.io
  resources:
  - sessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - desktops.kvdi.io
  resources:
  - sessions/status
  verbs:
  - get
