name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE_DEP_PATH: go.sum
  GO_VERSION: 1.21

jobs:
  setup:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: false

      - name: Setup Test Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-tests-go-${{ env.GO_VERSION }}-${{ hashFiles(env.CACHE_DEP_PATH) }}
          restore-keys: ${{ runner.os }}-tests-go-${{ env.GO_VERSION }}-
          path: |
            ~/go/pkg
            ~/go/bin
            ~/.cache/go-build

      - name: Static Analysis
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          args: --timeout 10m
          skip-pkg-cache: true

      - name: Unit Tests
        run: make test
